"""Wave 1512 — residual-span coverage round-out for PDAppearanceGenerator.

Exercises two real, upstream-faithful spans that the existing rich-text /
font-resolution suites never reach because they always start from a widget
that already carries an ``/AP`` (auto-generated by ``set_value``):

- ``_regenerate_rich_text_widget`` creating a *fresh* ``/AP`` dictionary on a
  widget that has none yet (the ``else`` branch of the ``/AP`` lookup).
- ``_coerce_to_pd_font`` wrapping a raw ``COSDictionary`` font entry handed in
  directly (the defensive branch the docstring documents).
"""

from __future__ import annotations

from pypdfbox.cos import COSArray, COSDictionary, COSFloat, COSName, COSStream
from pypdfbox.pdmodel.font.pd_font import PDFont
from pypdfbox.pdmodel.interactive.annotation.pd_appearance_dictionary import (
    PDAppearanceDictionary,
)
from pypdfbox.pdmodel.interactive.form import PDAcroForm, PDAppearanceGenerator
from pypdfbox.pdmodel.interactive.form.pd_text_field import PDTextField

_RECT: COSName = COSName.get_pdf_name("Rect")
_AP: COSName = COSName.get_pdf_name("AP")
_DA: COSName = COSName.get_pdf_name("DA")
_RV: COSName = COSName.get_pdf_name("RV")
_SUBTYPE: COSName = COSName.get_pdf_name("Subtype")
_BASE_FONT: COSName = COSName.get_pdf_name("BaseFont")


def _rect(llx: float, lly: float, urx: float, ury: float) -> COSArray:
    return COSArray(
        [COSFloat(llx), COSFloat(lly), COSFloat(urx), COSFloat(ury)]
    )


def test_rich_text_creates_fresh_ap_when_widget_has_none() -> None:
    """Rich-text regen must create + attach a new ``/AP`` dict when the
    widget carries none yet (the ``else`` branch, lines 1855-1856).

    We suppress ``set_value``'s auto-generation so the widget reaches
    ``generate`` with no ``/AP``, then drive ``generate`` directly.
    """
    form = PDAcroForm()
    tf = PDTextField(form)
    cos = tf.get_cos_object()
    cos.set_item(_RECT, _rect(0.0, 0.0, 300.0, 60.0))
    cos.set_string(_DA, "/Helv 12 Tf 0 0 0 rg")
    cos.set_string(_RV, "<body><p><b>Bold</b> text</p></body>")
    # regenerate_appearance=False -> no /AP is created here.
    tf.set_value("Bold text", regenerate_appearance=False)

    widget_cos = tf.get_widgets()[0].get_cos_object()
    assert widget_cos.get_dictionary_object(_AP) is None

    PDAppearanceGenerator().generate(tf)

    ap_value = widget_cos.get_dictionary_object(_AP)
    assert isinstance(ap_value, COSDictionary)
    ap = PDAppearanceDictionary(ap_value)
    normal = ap.get_normal_appearance()
    assert normal is not None
    normal_cos = normal.get_cos_object()
    assert isinstance(normal_cos, COSStream)
    body = normal_cos.create_input_stream().read()
    # /Tx BMC marker proves the rich-text content stream was emitted.
    assert b"/Tx BMC" in body


def test_coerce_to_pd_font_wraps_raw_cos_dictionary() -> None:
    """``_coerce_to_pd_font`` wraps a raw font ``COSDictionary`` via
    ``PDFontFactory.create_font`` (defensive branch, line 2866)."""
    font_dict = COSDictionary()
    font_dict.set_name(_SUBTYPE, "Type1")
    font_dict.set_name(_BASE_FONT, "Helvetica")

    result = PDAppearanceGenerator._coerce_to_pd_font(font_dict)

    assert isinstance(result, PDFont)


def test_coerce_to_pd_font_passthrough_and_none() -> None:
    """A typed ``PDFont`` is returned as-is; ``None`` / other types -> ``None``."""
    font_dict = COSDictionary()
    font_dict.set_name(_SUBTYPE, "Type1")
    font_dict.set_name(_BASE_FONT, "Helvetica")
    pd_font = PDAppearanceGenerator._coerce_to_pd_font(font_dict)
    assert pd_font is not None
    # Idempotent: feeding the typed instance back returns the same object.
    assert PDAppearanceGenerator._coerce_to_pd_font(pd_font) is pd_font
    assert PDAppearanceGenerator._coerce_to_pd_font(None) is None
    assert PDAppearanceGenerator._coerce_to_pd_font("not a font") is None
