"""Live Apache PDFBox differential parity for the *combined* fontbox CFF
**charset + built-in encoding + name->GID** surface of a non-CID CFF that
carries a custom charset AND a custom embedded /Encoding in the same font.

The sibling oracles isolate the two surfaces:

* ``test_cff_charset_oracle.py`` exercises ``CFFFont.getCharset()`` across
  every on-disk charset format, but all of its name-keyed fonts keep the
  default (Standard) /Encoding.
* ``test_cff_encoding_oracle.py`` exercises ``CFFType1Font.getEncoding()``
  for the predefined IDs (Standard / Expert) and one real-world embedded
  Format0 program, but never on a font whose *charset* is also custom and
  never via the ``nameToGID`` round-trip.

This oracle is the cross-product: on a single synthetic font whose charset
maps GIDs to custom SIDs (>= 391, names in the local STRING INDEX) **and**
whose /Encoding is an embedded table, it asserts that all three
resolutions agree with PDFBox 3.0.7:

* ``getCharset().getNameForGID`` / ``getSIDForGID`` (GID -> name / SID),
* ``getEncoding().getName`` (code -> name), including the encoding *class*
  identity, and
* ``CFFType1Font.nameToGID`` — the round-trip that ties an encoded byte
  (code -> name via the encoding) back to a glyph index (name -> GID via
  the charset).

The high-value differential is the encoding *class*. fontTools decompiles
*both* the on-disk Format0 and Format1 encoding tables into an identical
256-name list and discards the format byte; the only way to recover the
``Format0Encoding`` vs ``Format1Encoding`` identity PDFBox exposes is to
re-read the format byte at the raw Encoding offset. The
``custom_charset_fmt1_enc.cff`` fixture (a contiguous code run fontTools
compresses into a Format1 range table) is the case that pins that down —
before the fix pypdfbox surfaced it as ``Format0Encoding``.

Fixtures are regenerated byte-for-byte by
``tests/fixtures/fontbox/cff/make_charset_encoding_fixtures.py``. Both
engines read the *same* CFF bytes, so any divergence is a real
resolution bug, not a byte-layout artifact.
"""

from __future__ import annotations

from pathlib import Path

from pypdfbox.fontbox.cff.cff_parser import CFFParser
from pypdfbox.fontbox.cff.cff_type1_font import CFFType1Font
from tests.oracle.harness import requires_oracle, run_probe_text

_REPO = Path(__file__).resolve().parents[4]
_CFF_FIXTURES = _REPO / "tests" / "fixtures" / "fontbox" / "cff"

_FMT0 = _CFF_FIXTURES / "custom_charset_fmt0_enc.cff"
_FMT1 = _CFF_FIXTURES / "custom_charset_fmt1_enc.cff"


# --------------------------------------------------------------------------- #
# Probe-line parsing — see oracle/probes/CffCharsetEncodingProbe.java.
# --------------------------------------------------------------------------- #


class _Facts:
    def __init__(self) -> None:
        self.font_class: str = ""
        self.is_cid: str = ""
        self.n_glyphs: int = 0
        self.enc_class: str = ""
        self.code_map: dict[int, str] = {}
        self.name: dict[int, str] = {}
        self.sid: dict[int, int] = {}
        self.name_to_gid: dict[str, int] = {}
        self.code_to_gid: dict[int, int] = {}


def _parse_probe(text: str) -> _Facts:
    f = _Facts()
    for line in text.splitlines():
        cols = line.split("\t")
        tag = cols[0]
        if tag == "FONT" and len(cols) >= 2:
            f.font_class = cols[1]
        elif tag == "CID" and len(cols) >= 2:
            f.is_cid = cols[1]
        elif tag == "NGLYPH" and len(cols) >= 2:
            f.n_glyphs = int(cols[1])
        elif tag == "ENC" and len(cols) >= 2:
            f.enc_class = cols[1]
        elif tag == "MAP" and len(cols) >= 3:
            f.code_map[int(cols[1])] = cols[2]
        elif tag == "NAME" and len(cols) >= 3:
            f.name[int(cols[1])] = cols[2]
        elif tag == "SID" and len(cols) >= 3:
            f.sid[int(cols[1])] = int(cols[2])
        elif tag == "N2G" and len(cols) >= 3:
            f.name_to_gid[cols[1]] = int(cols[2])
        elif tag == "E2G" and len(cols) >= 3:
            f.code_to_gid[int(cols[1])] = int(cols[2])
    return f


# --------------------------------------------------------------------------- #
# pypdfbox-side fact extraction — mirrors the probe field-for-field.
# --------------------------------------------------------------------------- #


def _py_facts(data: bytes) -> _Facts:
    f = _Facts()
    font = CFFParser().parse(data)[0]
    f.font_class = type(font).__name__
    f.is_cid = "true" if font.is_cid_font() else "false"
    f.n_glyphs = len(font.get_char_string_bytes())
    assert isinstance(font, CFFType1Font)
    enc = font.get_encoding()
    f.enc_class = type(enc).__name__
    for code in range(256):
        name = enc.get_name(code)
        if name and name != ".notdef":
            f.code_map[code] = name
    for gid in range(f.n_glyphs):
        name = font.get_name_for_gid(gid)
        f.name[gid] = name
        f.sid[gid] = font.get_sid_for_gid(gid)
        if name is not None:
            f.name_to_gid[name] = font.name_to_gid(name)
    for code, name in f.code_map.items():
        f.code_to_gid[code] = font.name_to_gid(name)
    return f


def _assert_parity(probe_text: str, data: bytes) -> None:
    java = _parse_probe(probe_text)
    py = _py_facts(data)
    assert py.font_class == java.font_class, (
        "font_class",
        py.font_class,
        java.font_class,
    )
    assert py.is_cid == java.is_cid, ("is_cid", py.is_cid, java.is_cid)
    assert py.n_glyphs == java.n_glyphs, (
        "n_glyphs",
        py.n_glyphs,
        java.n_glyphs,
    )
    # Load-bearing: the Format0 vs Format1 embedded-encoding class identity.
    assert py.enc_class == java.enc_class, (
        "enc_class",
        py.enc_class,
        java.enc_class,
    )
    assert py.code_map == java.code_map, (
        "code_map",
        py.code_map,
        java.code_map,
    )
    assert py.name == java.name, ("name map", py.name, java.name)
    assert py.sid == java.sid, ("sid map", py.sid, java.sid)
    assert py.name_to_gid == java.name_to_gid, (
        "name_to_gid map",
        py.name_to_gid,
        java.name_to_gid,
    )
    assert py.code_to_gid == java.code_to_gid, (
        "code_to_gid map",
        py.code_to_gid,
        java.code_to_gid,
    )


# --------------------------------------------------------------------------- #
# Differential tests.
# --------------------------------------------------------------------------- #


@requires_oracle
def test_custom_charset_format0_encoding_matches_pdfbox() -> None:
    """Custom charset + sparse embedded /Encoding (on-disk Format0).

    The sparse code->glyph assignment compiles to a flat ``(code, sid)``
    Format0 table; PDFBox surfaces it as ``Format0Encoding``. Every
    GID->name/SID, code->name, and ``nameToGID`` round-trip must match."""
    data = _FMT0.read_bytes()
    probe = run_probe_text("CffCharsetEncodingProbe", str(_FMT0))
    _assert_parity(probe, data)


@requires_oracle
def test_custom_charset_format1_encoding_matches_pdfbox() -> None:
    """Custom charset + contiguous embedded /Encoding (on-disk Format1).

    A contiguous code run compiles to a Format1 *range* table; PDFBox
    surfaces it as ``Format1Encoding``. fontTools decompiles it into the
    same 256-name list as a Format0 table and drops the format byte, so
    pypdfbox must re-read the on-disk format byte to recover the
    ``Format1Encoding`` class identity — this is the case that catches a
    parser that hard-wires every embedded encoding to ``Format0Encoding``."""
    data = _FMT1.read_bytes()
    probe = run_probe_text("CffCharsetEncodingProbe", str(_FMT1))
    _assert_parity(probe, data)
