"""Live Apache FontBox differential parity for the CFF *subroutine* glyph-PATH
surface — the assembled ``GeneralPath`` produced by
``CFFFont.getType2CharString(gid).getPath()`` for a font whose drawing
operators live *inside* local (``callsubr``) and global (``callgsubr``)
subroutines, reachable only through the CFF subr *bias* (107 / 1131 / 32768 by
INDEX size, Adobe Technote #5176 §16).

This is upstream-distinct from ``test_cff_type2_parse_oracle`` (which pins the
parser's flat *token stream*): here a wrong bias or broken subr-nesting
resolution shows up as a *wrong assembled outline*, so the path fingerprint is
the sharper regression pin for the ``calculateSubrNumber`` + recursive
``callsubr`` / ``callgsubr`` inlining path.

Fixture
-------
``subr_path.cff`` — a synthetic *name-keyed* (Type1C) CFF generated by
``tests/fixtures/fontbox/cff/make_subr_path_fixture.py`` (fontTools
``CFFFontSet.compile``, MIT). Its local /Subrs INDEX is padded past 1240 entries
so its bias is **1131** (not 107) while the global subrs INDEX stays small
(bias **107**); glyphs draw exclusively *through* subrs:

* ``Aloc`` draws via a local subr (1131-bias ``callsubr``);
* ``Bglob`` draws via a global subr (107-bias ``callgsubr``);
* ``Cnest`` nests local subr -> ``callgsubr`` (recursive resolution);
* ``Dmix`` mixes a local-subr curve and a global-subr line in one path.

Both engines parse the *same* CFF bytes through their respective Type 2
charstring interpreter; any divergence in the assembled path is a real
subr-resolution / bias bug, not a byte-layout artifact.

The probe (``CffSubrPathProbe``) emits a COORDINATE-TOLERANT but
STRUCTURALLY-STRICT fingerprint identical to ``GlyphPathProbe``: the rounded
control-point bounding box (Java ``Path2D.getBounds2D`` evaluates Bezier
extrema), the segment count, and the M/L/Q/C/Z segment-type sequence from the
``PathIterator``. :func:`_pypdfbox_fingerprint` reproduces that fingerprint
from pypdfbox's ``get_path`` command list with the same TWO documented
normalisations onto the Java ``PathIterator`` sequence used by the Type 1
glyph-path oracle (these are representation differences, not bugs):

  1. **Trailing moveTo after each close.** Apache FontBox's
     ``Type2CharString.closeCharString2Path`` (via ``GeneralPath``) appends a
     ``moveTo(currentPoint)`` after every ``closePath()`` to prime the next
     sub-path. pypdfbox delegates ``get_path`` to fontTools' charstring
     ``draw``, which omits that no-op trailing moveTo; we re-insert it.
  2. **Consecutive-moveTo coalescing.** A ``GeneralPath`` collapses back-to-back
     ``moveTo`` calls into one ``SEG_MOVETO``, so a "close -> moveTo, then the
     next contour's rmoveto -> moveTo" pair shows up as ONE ``M``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from pypdfbox.fontbox.cff.cff_parser import CFFParser
from pypdfbox.fontbox.cff.cff_type1_font import CFFType1Font
from tests.oracle.harness import requires_oracle, run_probe_text

_REPO = Path(__file__).resolve().parents[4]
_CFF_FIXTURES = _REPO / "tests" / "fixtures" / "fontbox" / "cff"
_SUBR_CFF = _CFF_FIXTURES / "subr_path.cff"


# ---------------------------------------------------------------------------
# Curve-exact bbox helpers (mirror the TTF / Type1 / CFF glyph-path oracles).
# Java Path2D.getBounds2D evaluates Bezier extrema; a control point outside the
# rendered arc must NOT widen the box, so we solve each cubic's derivative.
# ---------------------------------------------------------------------------
def _cubic_extrema_t(p0: float, p1: float, p2: float, p3: float) -> list[float]:
    """Parameters t in (0, 1) where a cubic Bezier's coordinate is extremal."""
    a = -p0 + 3.0 * p1 - 3.0 * p2 + p3
    b = 2.0 * (p0 - 2.0 * p1 + p2)
    c = -p0 + p1
    out: list[float] = []
    if abs(a) < 1e-12:
        if abs(b) > 1e-12:
            t = -c / b
            if 0.0 < t < 1.0:
                out.append(t)
        return out
    disc = b * b - 4.0 * a * c
    if disc < 0.0:
        return out
    root = disc**0.5
    for t in ((-b + root) / (2.0 * a), (-b - root) / (2.0 * a)):
        if 0.0 < t < 1.0:
            out.append(t)
    return out


def _cubic_eval(p0: float, p1: float, p2: float, p3: float, t: float) -> float:
    mt = 1.0 - t
    return mt**3 * p0 + 3.0 * mt**2 * t * p1 + 3.0 * mt * t**2 * p2 + t**3 * p3


class _Fingerprint:
    """Mutable (bbox, nseg, type-sequence) accumulator."""

    def __init__(self) -> None:
        self.types: list[str] = []
        self.min_x: float | None = None
        self.min_y: float | None = None
        self.max_x: float | None = None
        self.max_y: float | None = None
        self._cur: tuple[float, float] | None = None
        self._start: tuple[float, float] | None = None

    def _point(self, x: float, y: float) -> None:
        if self.min_x is None:
            self.min_x = self.max_x = x
            self.min_y = self.max_y = y
            return
        self.min_x = min(self.min_x, x)
        self.max_x = max(self.max_x, x)
        self.min_y = min(self.min_y, y)
        self.max_y = max(self.max_y, y)

    def move(self, x: float, y: float) -> None:
        self.types.append("M")
        self._point(x, y)
        self._cur = (x, y)
        self._start = (x, y)

    def line(self, x: float, y: float) -> None:
        self.types.append("L")
        self._point(x, y)
        self._cur = (x, y)

    def cubic(
        self, c1x: float, c1y: float, c2x: float, c2y: float, x: float, y: float
    ) -> None:
        self.types.append("C")
        p0 = self._cur if self._cur is not None else (x, y)
        self._point(x, y)
        for axis in (0, 1):
            a0 = p0[axis]
            a1 = (c1x, c1y)[axis]
            a2 = (c2x, c2y)[axis]
            a3 = (x, y)[axis]
            for t in _cubic_extrema_t(a0, a1, a2, a3):
                ex = _cubic_eval(p0[0], c1x, c2x, x, t)
                ey = _cubic_eval(p0[1], c1y, c2y, y, t)
                self._point(ex, ey)
        self._cur = (x, y)

    def close(self) -> None:
        self.types.append("Z")
        if self._start is not None:
            self._cur = self._start

    def as_line(self) -> str:
        nseg = len(self.types)
        if nseg == 0:
            return "0 0 0 0 0 "
        assert self.min_x is not None
        assert self.min_y is not None
        assert self.max_x is not None
        assert self.max_y is not None
        return (
            f"{round(self.min_x)} {round(self.min_y)} "
            f"{round(self.max_x)} {round(self.max_y)} "
            f"{nseg} {''.join(self.types)}"
        )


def _pypdfbox_fingerprint(commands: list[tuple[Any, ...]]) -> str:
    """Normalise pypdfbox's ``get_path`` command list to the same ``PATH``
    payload the Java probe emits (bbox nseg typeSeq)."""
    ops: list[tuple[str, tuple[float, ...]]] = []
    current: tuple[float, float] = (0.0, 0.0)
    for cmd in commands:
        tag = cmd[0]
        if tag == "moveto":
            current = (float(cmd[1]), float(cmd[2]))
            ops.append(("M", current))
        elif tag == "lineto":
            current = (float(cmd[1]), float(cmd[2]))
            ops.append(("L", current))
        elif tag == "curveto":
            ops.append(
                (
                    "C",
                    (
                        float(cmd[1]),
                        float(cmd[2]),
                        float(cmd[3]),
                        float(cmd[4]),
                        float(cmd[5]),
                        float(cmd[6]),
                    ),
                )
            )
            current = (float(cmd[5]), float(cmd[6]))
        elif tag == "closepath":
            ops.append(("Z", ()))
            ops.append(("M", current))  # closeCharString2Path: moveTo(current)

    fp = _Fingerprint()
    for i, (kind, args) in enumerate(ops):
        if kind == "M":
            # GeneralPath keeps only the last of a run of consecutive moveTos.
            if i + 1 < len(ops) and ops[i + 1][0] == "M":
                continue
            fp.move(args[0], args[1])
        elif kind == "L":
            fp.line(args[0], args[1])
        elif kind == "C":
            fp.cubic(*args)
        elif kind == "Z":
            fp.close()
    return fp.as_line()


def _parse_probe(text: str) -> tuple[int, dict[int, str]]:
    """Parse ``CffSubrPathProbe read`` output into (num_glyphs, {gid: payload})."""
    num_glyphs = 0
    paths: dict[int, str] = {}
    for line in text.splitlines():
        cols = line.split("\t")
        if cols[0] == "META" and len(cols) >= 2:
            num_glyphs = int(cols[1])
        elif cols[0] == "PATH" and len(cols) >= 8:
            gid = int(cols[1])
            payload = " ".join(cols[2:7]) + " " + cols[7]
            paths[gid] = payload
    return num_glyphs, paths


@requires_oracle
def test_cff_subr_glyph_path_matches_pdfbox() -> None:
    assert _SUBR_CFF.is_file(), f"missing fixture: {_SUBR_CFF}"
    data = _SUBR_CFF.read_bytes()
    font = CFFParser().parse(data)[0]
    assert isinstance(font, CFFType1Font), "fixture must be a name-keyed CFF"

    java_num, java_paths = _parse_probe(
        run_probe_text("CffSubrPathProbe", "read", str(_SUBR_CFF))
    )
    py_num = font.get_num_char_strings()
    assert py_num == java_num, ("num_glyphs", py_num, java_num)
    assert set(java_paths) == set(range(py_num)), ("gid set", sorted(java_paths))

    diffs: list[str] = []
    for gid in sorted(java_paths):
        cs = font.get_type2_char_string(gid)
        py_payload = _pypdfbox_fingerprint(cs.get_path())
        if py_payload != java_paths[gid]:
            diffs.append(
                f"gid {gid} ({cs.get_name()}):\n  java={java_paths[gid]!r}\n"
                f"  py  ={py_payload!r}"
            )
    assert not diffs, "CFF subr glyph-path parity broken:\n" + "\n".join(diffs)
