"""Live Apache PDFBox differential parity for fontbox **CFF /charset**
resolution — the ``CFFFont.getCharset()`` surface across every on-disk
charset encoding plus a predefined charset.

The CFF charset table maps each GID to a SID (name-keyed fonts) or a CID
(CID-keyed fonts). It is stored in one of four ways (Adobe Technote #5176
§13):

* **Format 0** — a flat array of one SID/CID per glyph. ``std_enc.cff``
  (synthetic, non-contiguous SIDs) exercises this for a name-keyed font.
* **Format 1** — run-length ranges with a 1-byte ``nLeft``.
  ``charset_fmt1_name.cff`` (contiguous custom SIDs) for a name-keyed
  font; ``cid_multifd_3fd.cff`` for a CID-keyed font.
* **Format 2** — run-length ranges with a 2-byte ``nLeft`` (needed when a
  single contiguous run exceeds 256 glyphs). ``charset_fmt2_name.cff``
  (400 contiguous custom SIDs) is the only fixture that drives the
  2-byte ``nLeft`` read path.
* **Predefined** — the Top DICT ``/charset`` operand is a small id
  (0 = ISOAdobe, 1 = Expert, 2 = ExpertSubset) and there is *no*
  embedded charset table; the GID→name mapping comes from the
  font-independent canonical table. ``charset_iso_adobe.cff`` (a charset
  that is an exact prefix of ISOAdobe) drives the predefined path — the
  high-value bug being a parser that mis-reads the predefined id ``0`` as
  an offset into the program (landing on header bytes and producing
  garbage names).

The differential surface, per GID, is the full ``CFFCharset`` contract:

* name-keyed — ``getNameForGID`` (GID→PostScript name via SID→string),
  ``getSIDForGID`` / ``getGIDForSID`` round-trip, and ``getSID(name)``.
* CID-keyed — ``getCIDForGID`` and the ``getGIDForCID`` round-trip.

Both engines read the *same* CFF bytes, so any divergence is a real
charset-resolution bug, not a byte-layout artifact. The synthetic
fixtures are regenerated byte-for-byte by
``tests/fixtures/fontbox/cff/make_charset_fixtures.py`` (Format1 / Format2
/ ISOAdobe) and ``make_encoding_fixtures.py`` (the Format0 ``std_enc``).
"""

from __future__ import annotations

from pathlib import Path

from pypdfbox.fontbox.cff.cff_parser import CFFParser
from tests.oracle.harness import requires_oracle, run_probe_text

_REPO = Path(__file__).resolve().parents[4]
_CFF_FIXTURES = _REPO / "tests" / "fixtures" / "fontbox" / "cff"

_FORMAT0_NAME = _CFF_FIXTURES / "std_enc.cff"
_FORMAT1_NAME = _CFF_FIXTURES / "charset_fmt1_name.cff"
_FORMAT2_NAME = _CFF_FIXTURES / "charset_fmt2_name.cff"
_ISO_ADOBE = _CFF_FIXTURES / "charset_iso_adobe.cff"
_FORMAT1_CID = _CFF_FIXTURES / "cid_multifd_3fd.cff"


# --------------------------------------------------------------------------- #
# Probe-line parsing — see oracle/probes/CffCharsetProbe.java for the schema.
# --------------------------------------------------------------------------- #


class _CharsetFacts:
    def __init__(self) -> None:
        self.font_class: str = ""
        self.is_cid: str = ""
        self.n_glyphs: int = 0
        self.name: dict[int, str] = {}
        self.sid: dict[int, int] = {}
        self.gid_for_sid: dict[int, int] = {}
        self.sid_for_name: dict[str, int] = {}
        self.cid: dict[int, int] = {}
        self.gid_for_cid: dict[int, int] = {}


def _parse_probe(text: str) -> _CharsetFacts:
    f = _CharsetFacts()
    for line in text.splitlines():
        cols = line.split("\t")
        tag = cols[0]
        if tag == "FONT" and len(cols) >= 2:
            f.font_class = cols[1]
        elif tag == "CID" and len(cols) >= 2:
            f.is_cid = cols[1]
        elif tag == "NGLYPH" and len(cols) >= 2:
            f.n_glyphs = int(cols[1])
        elif tag == "NAME" and len(cols) >= 3:
            f.name[int(cols[1])] = cols[2]
        elif tag == "SID" and len(cols) >= 3:
            f.sid[int(cols[1])] = int(cols[2])
        elif tag == "GFS" and len(cols) >= 3:
            f.gid_for_sid[int(cols[1])] = int(cols[2])
        elif tag == "GSID" and len(cols) >= 3:
            f.sid_for_name[cols[1]] = int(cols[2])
        elif tag == "CIDG" and len(cols) >= 3:
            f.cid[int(cols[1])] = int(cols[2])
        elif tag == "GFC" and len(cols) >= 3:
            f.gid_for_cid[int(cols[1])] = int(cols[2])
    return f


# --------------------------------------------------------------------------- #
# pypdfbox-side fact extraction — mirrors the probe field-for-field.
# --------------------------------------------------------------------------- #


def _py_facts(data: bytes) -> _CharsetFacts:
    f = _CharsetFacts()
    font = CFFParser().parse(data)[0]
    f.font_class = type(font).__name__
    f.is_cid = "true" if font.is_cid_font() else "false"
    f.n_glyphs = len(font.get_char_string_bytes())
    if font.is_cid_font():
        for gid in range(f.n_glyphs):
            cid = font.get_cid_for_gid(gid)
            f.cid[gid] = cid
            f.gid_for_cid[cid] = font.get_gid_for_cid(cid)
    else:
        for gid in range(f.n_glyphs):
            name = font.get_name_for_gid(gid)
            sid = font.get_sid_for_gid(gid)
            f.name[gid] = name
            f.sid[gid] = sid
            f.gid_for_sid[sid] = font.get_gid_for_sid(sid)
            if name is not None:
                f.sid_for_name[name] = font.get_sid(name)
    return f


def _assert_charset_parity(probe_text: str, data: bytes) -> None:
    java = _parse_probe(probe_text)
    py = _py_facts(data)
    assert py.font_class == java.font_class, (
        "font_class",
        py.font_class,
        java.font_class,
    )
    assert py.is_cid == java.is_cid, ("is_cid", py.is_cid, java.is_cid)
    assert py.n_glyphs == java.n_glyphs, ("n_glyphs", py.n_glyphs, java.n_glyphs)
    # GID -> name / SID and the SID/name round-trips (name-keyed fonts).
    assert py.name == java.name, ("name map", py.name, java.name)
    assert py.sid == java.sid, ("sid map", py.sid, java.sid)
    assert py.gid_for_sid == java.gid_for_sid, (
        "gid_for_sid map",
        py.gid_for_sid,
        java.gid_for_sid,
    )
    assert py.sid_for_name == java.sid_for_name, (
        "sid_for_name map",
        py.sid_for_name,
        java.sid_for_name,
    )
    # GID -> CID and the CID round-trip (CID-keyed fonts).
    assert py.cid == java.cid, ("cid map", py.cid, java.cid)
    assert py.gid_for_cid == java.gid_for_cid, (
        "gid_for_cid map",
        py.gid_for_cid,
        java.gid_for_cid,
    )


# --------------------------------------------------------------------------- #
# Differential tests.
# --------------------------------------------------------------------------- #


@requires_oracle
def test_format0_name_charset_matches_pdfbox() -> None:
    """Name-keyed Format0 (flat SID array). Non-contiguous SIDs (A=34,
    B=35, space=1) force a Format0 table; every GID→name/SID and the
    round-trips match PDFBox's ``CFFCharsetType1``."""
    data = _FORMAT0_NAME.read_bytes()
    probe = run_probe_text("CffCharsetProbe", str(_FORMAT0_NAME))
    _assert_charset_parity(probe, data)


@requires_oracle
def test_format1_name_charset_matches_pdfbox() -> None:
    """Name-keyed Format1 (range table, 1-byte nLeft). Contiguous custom
    SIDs collapse to a single range; the per-GID name/SID resolution must
    still match the flat-array semantics PDFBox exposes."""
    data = _FORMAT1_NAME.read_bytes()
    probe = run_probe_text("CffCharsetProbe", str(_FORMAT1_NAME))
    _assert_charset_parity(probe, data)


@requires_oracle
def test_format2_name_charset_matches_pdfbox() -> None:
    """Name-keyed Format2 (range table, 2-byte nLeft). 400 contiguous SIDs
    exceed the 1-byte nLeft ceiling, forcing Format2 — the only encoding
    that drives the 2-byte nLeft read path. Every GID→name/SID matches."""
    data = _FORMAT2_NAME.read_bytes()
    probe = run_probe_text("CffCharsetProbe", str(_FORMAT2_NAME))
    _assert_charset_parity(probe, data)


@requires_oracle
def test_predefined_iso_adobe_charset_matches_pdfbox() -> None:
    """Predefined ISOAdobe charset (Top DICT operand 0, no embedded
    table). A charset that is an exact prefix of the ISOAdobe canonical
    table writes the predefined id 0; PDFBox resolves GID→name from the
    font-independent table. A parser that mis-reads the id 0 as an offset
    into the program would produce garbage names — this pins that down."""
    data = _ISO_ADOBE.read_bytes()
    probe = run_probe_text("CffCharsetProbe", str(_ISO_ADOBE))
    _assert_charset_parity(probe, data)


@requires_oracle
def test_format1_cid_charset_matches_pdfbox() -> None:
    """CID-keyed Format1 (range table). The GID→CID mapping and the
    ``getGIDForCID`` round-trip must match PDFBox's ``CFFCharsetCID`` for
    every glyph in the FontSet."""
    data = _FORMAT1_CID.read_bytes()
    probe = run_probe_text("CffCharsetProbe", str(_FORMAT1_CID))
    _assert_charset_parity(probe, data)
