import java.io.OutputStream;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import org.apache.pdfbox.cos.COSArray;
import org.apache.pdfbox.cos.COSDictionary;
import org.apache.pdfbox.cos.COSFloat;
import org.apache.pdfbox.cos.COSInteger;
import org.apache.pdfbox.cos.COSName;
import org.apache.pdfbox.cos.COSStream;
import org.apache.pdfbox.cos.COSString;
import org.apache.pdfbox.pdmodel.graphics.color.PDColorSpace;
import org.apache.pdfbox.pdmodel.graphics.color.PDDeviceCMYK;
import org.apache.pdfbox.pdmodel.graphics.color.PDDeviceGray;
import org.apache.pdfbox.pdmodel.graphics.color.PDDeviceN;
import org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB;
import org.apache.pdfbox.pdmodel.graphics.color.PDICCBased;
import org.apache.pdfbox.pdmodel.graphics.color.PDIndexed;
import org.apache.pdfbox.pdmodel.graphics.color.PDLab;
import org.apache.pdfbox.pdmodel.graphics.color.PDSeparation;

/**
 * Live oracle probe for the SPECIAL colour-space -&gt; RGB conversion surface
 * that {@code ColorSpaceProbe} does not cover: Separation {@code /All} and
 * {@code /None} colorants, a 3-colorant DeviceN, Indexed index clamping /
 * rounding edge cases over a non-RGB base, Lab with a custom {@code /Range},
 * and ICCBased (embedded sRGB profile and the N-component {@code /Alternate}
 * fallback when the profile is missing).
 *
 * Emits canonical {@code "csname comp... -> r g b"} lines (RGB 0-255 ints,
 * {@code round(component*255)} clamped to [0,255]) so the Python side only has
 * to reconstruct the matching pypdfbox spaces and the same inputs.
 *
 * argv[0] = path to a small sRGB .icc profile (generated by the Python test
 * via Pillow so both sides embed byte-identical profile bytes).
 *
 * Usage: java -cp &lt;pdfbox-app.jar&gt;:&lt;build&gt; ColorToRgbSpecialProbe srgb.icc
 */
public final class ColorToRgbSpecialProbe {

    static PrintStream out;

    static int clamp255(float v) {
        long r = Math.round((double) v * 255.0);
        if (r < 0) {
            return 0;
        }
        if (r > 255) {
            return 255;
        }
        return (int) r;
    }

    static void emit(String name, float[] comps, PDColorSpace cs) throws Exception {
        float[] rgb = cs.toRGB(comps);
        StringBuilder sb = new StringBuilder();
        sb.append(name);
        for (float c : comps) {
            sb.append(' ').append(fmt(c));
        }
        sb.append(" -> ");
        sb.append(clamp255(rgb[0])).append(' ');
        sb.append(clamp255(rgb[1])).append(' ');
        sb.append(clamp255(rgb[2]));
        out.println(sb.toString());
    }

    static String fmt(float v) {
        if (v == Math.rint(v) && !Float.isInfinite(v)) {
            return Integer.toString((int) v);
        }
        return Float.toString(v);
    }

    static COSDictionary type2(float[] c0, float[] c1, float n) {
        COSDictionary d = new COSDictionary();
        d.setInt(COSName.FUNCTION_TYPE, 2);
        COSArray domain = new COSArray();
        domain.add(new COSFloat(0));
        domain.add(new COSFloat(1));
        d.setItem(COSName.DOMAIN, domain);
        COSArray a0 = new COSArray();
        for (float v : c0) {
            a0.add(new COSFloat(v));
        }
        d.setItem(COSName.C0, a0);
        COSArray a1 = new COSArray();
        for (float v : c1) {
            a1.add(new COSFloat(v));
        }
        d.setItem(COSName.C1, a1);
        d.setItem(COSName.N, new COSFloat(n));
        return d;
    }

    static COSStream type4(float[] domain, float[] range, String ps) throws Exception {
        COSStream s = new COSStream();
        s.setInt(COSName.FUNCTION_TYPE, 4);
        COSArray dom = new COSArray();
        for (float v : domain) {
            dom.add(new COSFloat(v));
        }
        s.setItem(COSName.DOMAIN, dom);
        COSArray rng = new COSArray();
        for (float v : range) {
            rng.add(new COSFloat(v));
        }
        s.setItem(COSName.RANGE, rng);
        OutputStream os = s.createOutputStream();
        os.write(ps.getBytes("US-ASCII"));
        os.close();
        return s;
    }

    public static void main(String[] args) throws Exception {
        out = new PrintStream(System.out, true, "UTF-8");
        String iccPath = args.length > 0 ? args[0] : null;

        // ---------- Separation /All (Type-2 tint -> DeviceCMYK) ----------
        // /All paints every colorant; tint t -> (t, t, t, t) CMYK.
        COSArray sepAllArr = new COSArray();
        sepAllArr.add(COSName.SEPARATION);
        sepAllArr.add(COSName.getPDFName("All"));
        sepAllArr.add(COSName.DEVICECMYK);
        sepAllArr.add(type2(
            new float[] {0.0f, 0.0f, 0.0f, 0.0f},
            new float[] {1.0f, 1.0f, 1.0f, 1.0f},
            1.0f));
        PDSeparation sepAll = new PDSeparation(sepAllArr);
        emit("SepAll", new float[] {0.0f}, sepAll);
        emit("SepAll", new float[] {0.5f}, sepAll);
        emit("SepAll", new float[] {1.0f}, sepAll);

        // ---------- Separation /None (Type-2 tint -> DeviceCMYK) ----------
        // /None is a colorant that produces no marks at render time, but
        // toRGB still routes through the tint transform unchanged.
        // tint t -> (0, 0, 0, t) CMYK : ramp toward black via K.
        COSArray sepNoneArr = new COSArray();
        sepNoneArr.add(COSName.SEPARATION);
        sepNoneArr.add(COSName.getPDFName("None"));
        sepNoneArr.add(COSName.DEVICECMYK);
        sepNoneArr.add(type2(
            new float[] {0.0f, 0.0f, 0.0f, 0.0f},
            new float[] {0.0f, 0.0f, 0.0f, 1.0f},
            1.0f));
        PDSeparation sepNone = new PDSeparation(sepNoneArr);
        emit("SepNone", new float[] {0.0f}, sepNone);
        emit("SepNone", new float[] {0.5f}, sepNone);
        emit("SepNone", new float[] {1.0f}, sepNone);

        // ---------- Separation /All -> DeviceGray (Type-4 tint) ----------
        // Pure-grey alternate keeps this in the exact tier (no CMM).
        // single tint -> DeviceGray g = 1 - tint.
        COSArray sepGrayArr = new COSArray();
        sepGrayArr.add(COSName.SEPARATION);
        sepGrayArr.add(COSName.getPDFName("All"));
        sepGrayArr.add(COSName.DEVICEGRAY);
        sepGrayArr.add(type4(
            new float[] {0.0f, 1.0f},
            new float[] {0.0f, 1.0f},
            "{ 1 exch sub }"));
        PDSeparation sepGray = new PDSeparation(sepGrayArr);
        emit("SepAllGray", new float[] {0.0f}, sepGray);
        emit("SepAllGray", new float[] {0.25f}, sepGray);
        emit("SepAllGray", new float[] {1.0f}, sepGray);

        // ---------- DeviceN, 3 colorants (Type-4 tint -> DeviceCMYK) ----------
        // (a, b, c) -> CMYK (a, b, c, 0)
        COSArray dnNames = new COSArray();
        dnNames.add(COSName.getPDFName("SpotA"));
        dnNames.add(COSName.getPDFName("SpotB"));
        dnNames.add(COSName.getPDFName("SpotC"));
        COSArray dnArr = new COSArray();
        dnArr.add(COSName.DEVICEN);
        dnArr.add(dnNames);
        dnArr.add(COSName.DEVICECMYK);
        // stack in: a b c ; want out: a b c 0
        dnArr.add(type4(
            new float[] {0, 1, 0, 1, 0, 1},
            new float[] {0, 1, 0, 1, 0, 1, 0, 1},
            "{ 0 }"));
        PDDeviceN devicen3 = new PDDeviceN(dnArr);
        emit("DeviceN3", new float[] {0.0f, 0.0f, 0.0f}, devicen3);
        emit("DeviceN3", new float[] {1.0f, 0.0f, 0.0f}, devicen3);
        emit("DeviceN3", new float[] {0.0f, 1.0f, 0.0f}, devicen3);
        emit("DeviceN3", new float[] {0.0f, 0.0f, 1.0f}, devicen3);
        emit("DeviceN3", new float[] {0.3f, 0.6f, 0.9f}, devicen3);

        // ---------- DeviceN, 3 colorants -> DeviceGray (Type-4) ----------
        // (a,b,c) -> gray = 1 - (a+b+c)/3  (exact tier: pure grey alternate)
        COSArray dngNames = new COSArray();
        dngNames.add(COSName.getPDFName("G1"));
        dngNames.add(COSName.getPDFName("G2"));
        dngNames.add(COSName.getPDFName("G3"));
        COSArray dngArr = new COSArray();
        dngArr.add(COSName.DEVICEN);
        dngArr.add(dngNames);
        dngArr.add(COSName.DEVICEGRAY);
        // in: a b c -> out one value: 1 - (a+b+c)/3
        dngArr.add(type4(
            new float[] {0, 1, 0, 1, 0, 1},
            new float[] {0, 1},
            "{ add add 3 div 1 exch sub }"));
        PDDeviceN devicenGray = new PDDeviceN(dngArr);
        emit("DeviceN3Gray", new float[] {0.0f, 0.0f, 0.0f}, devicenGray);
        emit("DeviceN3Gray", new float[] {1.0f, 1.0f, 1.0f}, devicenGray);
        emit("DeviceN3Gray", new float[] {0.3f, 0.6f, 0.9f}, devicenGray);

        // ---------- Indexed over DeviceGray base, hival 2 ----------
        // base = DeviceGray (1 comp), palette = {0x00, 0x80, 0xFF}.
        byte[] grayPalette = new byte[] {(byte) 0, (byte) 128, (byte) 255};
        COSArray idxGrayArr = new COSArray();
        idxGrayArr.add(COSName.INDEXED);
        idxGrayArr.add(COSName.DEVICEGRAY);
        idxGrayArr.add(COSInteger.get(2));
        idxGrayArr.add(new COSString(grayPalette));
        PDIndexed idxGray = (PDIndexed) PDColorSpace.create(idxGrayArr);
        // index clamping + rounding edge cases:
        emit("IdxGray", new float[] {-1.0f}, idxGray); // clamp low -> 0
        emit("IdxGray", new float[] {0.0f}, idxGray);
        emit("IdxGray", new float[] {0.4f}, idxGray);  // round -> 0
        emit("IdxGray", new float[] {0.6f}, idxGray);  // round -> 1
        emit("IdxGray", new float[] {1.0f}, idxGray);
        emit("IdxGray", new float[] {2.0f}, idxGray);
        emit("IdxGray", new float[] {5.0f}, idxGray);  // clamp high -> 2

        // ---------- Indexed over DeviceRGB base, hival 1, extra lookup bytes ----------
        // lookup carries 3 entries' worth of bytes but hival=1, so only the
        // first two entries are valid; index>1 clamps to the actual max.
        byte[] rgbPalette = new byte[] {
            (byte) 10, (byte) 20, (byte) 30,
            (byte) 200, (byte) 100, (byte) 50,
            (byte) 255, (byte) 255, (byte) 255 // beyond hival, must be ignored
        };
        COSArray idxRgbArr = new COSArray();
        idxRgbArr.add(COSName.INDEXED);
        idxRgbArr.add(COSName.DEVICERGB);
        idxRgbArr.add(COSInteger.get(1));
        idxRgbArr.add(new COSString(rgbPalette));
        PDIndexed idxRgb = (PDIndexed) PDColorSpace.create(idxRgbArr);
        emit("IdxRgb", new float[] {0.0f}, idxRgb);
        emit("IdxRgb", new float[] {1.0f}, idxRgb);
        emit("IdxRgb", new float[] {2.0f}, idxRgb); // clamp to hival=1

        // ---------- Lab with a custom /Range (asymmetric) ----------
        COSArray labArr = new COSArray();
        labArr.add(COSName.LAB);
        COSDictionary labDict = new COSDictionary();
        COSArray wpD50 = new COSArray();
        wpD50.add(new COSFloat(0.9642f));
        wpD50.add(new COSFloat(1.0f));
        wpD50.add(new COSFloat(0.8249f));
        labDict.setItem(COSName.WHITE_POINT, wpD50);
        COSArray labRange = new COSArray();
        labRange.add(new COSFloat(-100));
        labRange.add(new COSFloat(100));
        labRange.add(new COSFloat(-100));
        labRange.add(new COSFloat(100));
        labDict.setItem(COSName.RANGE, labRange);
        labArr.add(labDict);
        PDLab lab = new PDLab(labArr);
        emit("LabCustom", new float[] {25.0f, 60.0f, -60.0f}, lab);
        emit("LabCustom", new float[] {90.0f, -30.0f, 70.0f}, lab);
        emit("LabCustom", new float[] {0.0f, 0.0f, 0.0f}, lab);

        // ---------- ICCBased N=3 with embedded sRGB profile ----------
        if (iccPath != null) {
            byte[] iccBytes = Files.readAllBytes(Paths.get(iccPath));
            COSStream iccStream = new COSStream();
            iccStream.setInt(COSName.N, 3);
            OutputStream ios = iccStream.createOutputStream();
            ios.write(iccBytes);
            ios.close();
            COSArray iccArr = new COSArray();
            iccArr.add(COSName.ICCBASED);
            iccArr.add(iccStream);
            PDICCBased icc = (PDICCBased) PDColorSpace.create(iccArr);
            emit("IccSrgb", new float[] {0.0f, 0.0f, 0.0f}, icc);
            emit("IccSrgb", new float[] {1.0f, 0.0f, 0.0f}, icc);
            emit("IccSrgb", new float[] {0.25f, 0.5f, 0.75f}, icc);
            emit("IccSrgb", new float[] {1.0f, 1.0f, 1.0f}, icc);
        }

        // ---------- ICCBased N=3, empty profile, /Alternate DeviceRGB ----------
        // No (or unreadable) profile -> PDFBox + pypdfbox both fall back to
        // the alternate. DeviceRGB alternate keeps this in the exact tier.
        COSStream iccEmpty3 = new COSStream();
        iccEmpty3.setInt(COSName.N, 3);
        iccEmpty3.setItem(COSName.ALTERNATE, COSName.DEVICERGB);
        OutputStream e3 = iccEmpty3.createOutputStream();
        e3.write(new byte[0]);
        e3.close();
        COSArray iccEmpty3Arr = new COSArray();
        iccEmpty3Arr.add(COSName.ICCBASED);
        iccEmpty3Arr.add(iccEmpty3);
        PDICCBased iccFallbackRgb = (PDICCBased) PDColorSpace.create(iccEmpty3Arr);
        emit("IccFallbackRgb", new float[] {0.0f, 0.0f, 0.0f}, iccFallbackRgb);
        emit("IccFallbackRgb", new float[] {1.0f, 0.0f, 0.0f}, iccFallbackRgb);
        emit("IccFallbackRgb", new float[] {0.25f, 0.5f, 0.75f}, iccFallbackRgb);

        // ---------- ICCBased N=1, empty profile, /Alternate DeviceGray ----------
        COSStream iccEmpty1 = new COSStream();
        iccEmpty1.setInt(COSName.N, 1);
        iccEmpty1.setItem(COSName.ALTERNATE, COSName.DEVICEGRAY);
        OutputStream e1 = iccEmpty1.createOutputStream();
        e1.write(new byte[0]);
        e1.close();
        COSArray iccEmpty1Arr = new COSArray();
        iccEmpty1Arr.add(COSName.ICCBASED);
        iccEmpty1Arr.add(iccEmpty1);
        PDICCBased iccFallbackGray = (PDICCBased) PDColorSpace.create(iccEmpty1Arr);
        emit("IccFallbackGray", new float[] {0.0f}, iccFallbackGray);
        emit("IccFallbackGray", new float[] {0.5f}, iccFallbackGray);
        emit("IccFallbackGray", new float[] {1.0f}, iccFallbackGray);

        // ---------- ICCBased N=4, empty profile, /Alternate DeviceCMYK ----------
        // CMYK alternate -> documented-divergence tier (subtractive vs ICC).
        COSStream iccEmpty4 = new COSStream();
        iccEmpty4.setInt(COSName.N, 4);
        iccEmpty4.setItem(COSName.ALTERNATE, COSName.DEVICECMYK);
        OutputStream e4 = iccEmpty4.createOutputStream();
        e4.write(new byte[0]);
        e4.close();
        COSArray iccEmpty4Arr = new COSArray();
        iccEmpty4Arr.add(COSName.ICCBASED);
        iccEmpty4Arr.add(iccEmpty4);
        PDICCBased iccFallbackCmyk = (PDICCBased) PDColorSpace.create(iccEmpty4Arr);
        emit("IccFallbackCmyk", new float[] {0.0f, 0.0f, 0.0f, 0.0f}, iccFallbackCmyk);
        emit("IccFallbackCmyk", new float[] {0.0f, 0.0f, 0.0f, 1.0f}, iccFallbackCmyk);
        emit("IccFallbackCmyk", new float[] {1.0f, 0.0f, 0.0f, 0.0f}, iccFallbackCmyk);
        emit("IccFallbackCmyk", new float[] {0.2f, 0.4f, 0.6f, 0.1f}, iccFallbackCmyk);
    }
}
