import java.io.File;
import java.io.PrintStream;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.contentstream.operator.Operator;
import org.apache.pdfbox.cos.COSBase;
import org.apache.pdfbox.cos.COSName;
import org.apache.pdfbox.cos.COSNumber;
import org.apache.pdfbox.pdfparser.PDFStreamParser;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.graphics.color.PDColor;
import org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB;
import org.apache.pdfbox.pdmodel.interactive.annotation.PDAnnotation;
import org.apache.pdfbox.pdmodel.interactive.annotation.PDAnnotationCaret;
import org.apache.pdfbox.pdmodel.interactive.annotation.PDAnnotationRubberStamp;
import org.apache.pdfbox.pdmodel.interactive.annotation.PDAppearanceDictionary;
import org.apache.pdfbox.pdmodel.interactive.annotation.PDAppearanceEntry;
import org.apache.pdfbox.pdmodel.interactive.annotation.PDAppearanceStream;

/**
 * Live oracle probe for STAMP (PDAnnotationRubberStamp) and CARET
 * (PDAnnotationCaret) annotations.
 *
 * STAMP surface: the /Name standard-icon accessor — getName() (default DRAFT
 * when /Name absent) and setName(). Several rubber-stamp annotations are
 * written, one per page, each with a different /Name (or none); the read pass
 * emits each annotation's /Name string. NoName0 leaves /Name unset to pin the
 * NAME_DRAFT default.
 *
 * CARET surface: getRectDifferences() / setRectDifferences() AND the OPERAND-
 * LEVEL /AP /N content generated by PDCaretAppearanceHandler (driven via
 * PDAnnotationCaret.constructAppearances(doc)). The no-/RD path auto-creates
 * /RD = min(height/10, 5) on all four sides and enlarges /Rect + /BBox; the
 * pre-set-/RD path leaves /Rect untouched and uses the rect-sized BBox. The
 * filled Bezier "tooth" token stream is emitted byte-for-byte.
 *
 * Modes:
 *   java ... StampCaretProbe write out.pdf
 *   java ... StampCaretProbe read  out.pdf
 *
 * read output, per annotation (in /Annots order), keyed STAMP<n> / CARET<n>:
 *   STAMP record:
 *     ANNOT STAMP<idx>
 *     NAME <name string>
 *     END
 *   CARET record:
 *     ANNOT CARET<idx>
 *     RD <a>,<b>,<c>,<d>            (or "empty" when /RD absent)
 *     RECT <x0>,<y0>,<x1>,<y1>
 *     BBOX <x0>,<y0>,<x1>,<y1>     (or "NOAP")
 *     TOK <canonical token>         one per /AP /N content token
 *     END
 */
public final class StampCaretProbe {
    public static void main(String[] args) throws Exception {
        String mode = args[0];
        File file = new File(args[1]);
        if ("write".equals(mode)) {
            write(file);
        } else {
            read(file);
        }
    }

    private static PDColor rgb(float r, float g, float b) {
        return new PDColor(new float[] {r, g, b}, PDDeviceRGB.INSTANCE);
    }

    private static void write(File file) throws Exception {
        try (PDDocument doc = new PDDocument()) {
            // --- STAMP page: rubber-stamp annotations on one page ---
            PDPage sp = new PDPage(PDRectangle.A4);
            doc.addPage(sp);

            // 0: no /Name set -> getName() defaults to DRAFT
            PDAnnotationRubberStamp s0 = new PDAnnotationRubberStamp();
            s0.setRectangle(new PDRectangle(50, 700, 150, 40));
            sp.getAnnotations().add(s0);

            // 1: explicit Approved
            PDAnnotationRubberStamp s1 = new PDAnnotationRubberStamp();
            s1.setRectangle(new PDRectangle(50, 650, 150, 40));
            s1.setName(PDAnnotationRubberStamp.NAME_APPROVED);
            sp.getAnnotations().add(s1);

            // 2: explicit Confidential
            PDAnnotationRubberStamp s2 = new PDAnnotationRubberStamp();
            s2.setRectangle(new PDRectangle(50, 600, 150, 40));
            s2.setName(PDAnnotationRubberStamp.NAME_CONFIDENTIAL);
            sp.getAnnotations().add(s2);

            // 3: explicit TopSecret
            PDAnnotationRubberStamp s3 = new PDAnnotationRubberStamp();
            s3.setRectangle(new PDRectangle(50, 550, 150, 40));
            s3.setName(PDAnnotationRubberStamp.NAME_TOP_SECRET);
            sp.getAnnotations().add(s3);

            // 4: non-standard custom name (round-trips verbatim)
            PDAnnotationRubberStamp s4 = new PDAnnotationRubberStamp();
            s4.setRectangle(new PDRectangle(50, 500, 150, 40));
            s4.setName("MyCustomStamp");
            sp.getAnnotations().add(s4);

            // 5: explicitly set to NAME_DRAFT (matches default, present in dict)
            PDAnnotationRubberStamp s5 = new PDAnnotationRubberStamp();
            s5.setRectangle(new PDRectangle(50, 450, 150, 40));
            s5.setName(PDAnnotationRubberStamp.NAME_DRAFT);
            sp.getAnnotations().add(s5);

            // --- CARET 0: no /RD -> handler auto-creates /RD + enlarges rect ---
            PDPage cp0 = new PDPage(PDRectangle.A4);
            doc.addPage(cp0);
            PDAnnotationCaret c0 = new PDAnnotationCaret();
            c0.setRectangle(new PDRectangle(100, 600, 80, 40));
            c0.setColor(rgb(1, 0, 0));
            c0.constructAppearances(doc);
            cp0.getAnnotations().add(c0);

            // --- CARET 1: pre-set uniform /RD -> rect untouched, rect-sized bbox ---
            PDPage cp1 = new PDPage(PDRectangle.A4);
            doc.addPage(cp1);
            PDAnnotationCaret c1 = new PDAnnotationCaret();
            c1.setRectangle(new PDRectangle(100, 400, 80, 40));
            c1.setColor(rgb(0, 0, 1));
            c1.setRectDifferences(3);
            c1.constructAppearances(doc);
            cp1.getAnnotations().add(c1);

            // --- CARET 2: pre-set LRTB /RD ---
            PDPage cp2 = new PDPage(PDRectangle.A4);
            doc.addPage(cp2);
            PDAnnotationCaret c2 = new PDAnnotationCaret();
            c2.setRectangle(new PDRectangle(100, 200, 60, 100));
            c2.setColor(rgb(0.2f, 0.4f, 0.6f));
            c2.setRectDifferences(2, 4, 6, 8);
            c2.constructAppearances(doc);
            cp2.getAnnotations().add(c2);

            // --- CARET 3: tall rect, no /RD -> rd capped at 5 (height/10 > 5) ---
            PDPage cp3 = new PDPage(PDRectangle.A4);
            doc.addPage(cp3);
            PDAnnotationCaret c3 = new PDAnnotationCaret();
            c3.setRectangle(new PDRectangle(100, 100, 50, 120));
            c3.setColor(rgb(0, 0.5f, 0));
            c3.constructAppearances(doc);
            cp3.getAnnotations().add(c3);

            doc.save(file);
        }
    }

    private static void read(File file) throws Exception {
        PrintStream out = new PrintStream(System.out, true, "UTF-8");
        StringBuilder sb = new StringBuilder();
        try (PDDocument doc = Loader.loadPDF(file)) {
            int stampIdx = 0;
            int caretIdx = 0;
            for (PDPage page : doc.getPages()) {
                for (PDAnnotation annot : page.getAnnotations()) {
                    if (annot instanceof PDAnnotationRubberStamp) {
                        emitStamp(sb, (PDAnnotationRubberStamp) annot, stampIdx++);
                    } else if (annot instanceof PDAnnotationCaret) {
                        emitCaret(sb, (PDAnnotationCaret) annot, caretIdx++);
                    }
                }
            }
        }
        out.print(sb);
    }

    private static void emitStamp(StringBuilder sb, PDAnnotationRubberStamp s, int idx) {
        sb.append("ANNOT STAMP").append(idx).append('\n');
        sb.append("NAME ").append(s.getName()).append('\n');
        sb.append("END\n");
    }

    private static void emitCaret(StringBuilder sb, PDAnnotationCaret c, int idx) throws Exception {
        sb.append("ANNOT CARET").append(idx).append('\n');
        float[] rd = c.getRectDifferences();
        if (rd.length == 0) {
            sb.append("RD empty\n");
        } else {
            StringBuilder r = new StringBuilder();
            for (int i = 0; i < rd.length; i++) {
                if (i > 0) {
                    r.append(',');
                }
                r.append(canon(rd[i]));
            }
            sb.append("RD ").append(r).append('\n');
        }
        sb.append("RECT ").append(rectStr(c.getRectangle())).append('\n');

        PDAppearanceStream stream = normalStream(c);
        if (stream == null) {
            sb.append("BBOX NOAP\nEND\n");
            return;
        }
        sb.append("BBOX ").append(rectStr(stream.getBBox())).append('\n');
        PDFStreamParser parser = new PDFStreamParser(stream);
        List<Object> tokens = parser.parse();
        for (Object tok : tokens) {
            sb.append("TOK ").append(canonToken(tok)).append('\n');
        }
        sb.append("END\n");
    }

    private static String canonToken(Object tok) {
        if (tok instanceof Operator) {
            return ((Operator) tok).getName();
        }
        if (tok instanceof COSNumber) {
            return canon(((COSNumber) tok).floatValue());
        }
        if (tok instanceof COSName) {
            return "/" + ((COSName) tok).getName();
        }
        if (tok instanceof COSBase) {
            return tok.getClass().getSimpleName();
        }
        return String.valueOf(tok);
    }

    private static String rectStr(PDRectangle r) {
        if (r == null) {
            return "none";
        }
        return canon(r.getLowerLeftX()) + ","
                + canon(r.getLowerLeftY()) + ","
                + canon(r.getUpperRightX()) + ","
                + canon(r.getUpperRightY());
    }

    private static String canon(double value) {
        BigDecimal bd = new BigDecimal(Double.toString(value))
                .setScale(3, RoundingMode.HALF_EVEN)
                .stripTrailingZeros();
        String s = bd.toPlainString();
        if (s.equals("-0") || s.isEmpty()) {
            s = "0";
        }
        return s;
    }

    private static PDAppearanceStream normalStream(PDAnnotation annot) {
        PDAppearanceDictionary ap = annot.getAppearance();
        if (ap == null) {
            return null;
        }
        PDAppearanceEntry normal = ap.getNormalAppearance();
        if (normal == null || normal.isSubDictionary()) {
            return null;
        }
        return normal.getAppearanceStream();
    }
}
